# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestRegistroSpotify():
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def test_registroSpotify(self):
        self.driver.get("https://www.spotify.com/mx/signup/")
        self.driver.set_window_size(1550, 838)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("test18Spotify@gmail.com")
        self.driver.find_element(By.ID, "confirm").click()
        self.driver.find_element(By.ID, "confirm").click()
        self.driver.find_element(By.ID, "confirm").send_keys("test18Spotify@gmail.com")
        self.driver.find_element(By.ID, "password").send_keys("Test")
        self.driver.execute_script("window.scrollTo(0,211.1999969482422)")
        self.driver.find_element(By.ID, "displayname").click()
        self.driver.find_element(By.ID, "displayname").send_keys("Test18Spotify")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("TestContra")
        self.driver.find_element(By.ID, "day").click()
        self.driver.find_element(By.ID, "day").send_keys("14")
        self.driver.find_element(By.ID, "month").click()
        dropdown = self.driver.find_element(By.ID, "month")
        dropdown.find_element(By.XPATH, "//option[. = 'Junio']").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(7)").click()
        self.driver.find_element(By.ID, "year").click()
        self.driver.find_element(By.ID, "year").send_keys("1987")
        self.driver.find_element(By.CSS_SELECTOR, ".Radio-fatlcr-0:nth-child(2) > .Indicator-sc-16vj7o8-0").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()

    def tearDown(self):
        self.driver.quit()
